name: lm config
version: 1.0.0
schema: v1
models:
  - name: Qwen 3 vl
    provider: lm studio
    model: Qwen3-VL-30B-A3B-Thinking
    apiBase: http://100.83.43.121:1234/v1/
    roles:
      - chat
      - edit
      - apply
      - autocomplete
