---
name: autodetect
version: 1.2.0
schema: v1
models:
- name: autodetect
  provider: lmstudio
  model: autodetect
  apiBase: http://100.83.43.121:1234/v1/
  roles:
    - apply
    - autocomplete
    - chat
    - edit